import React,{useEffect,useMemo,useRef,useState}from"react";
import MazeCanvas from"./components/MazeCanvas";
import {cloneMaze,connected,has,makeMaze,sampleTwoPath,senseLocal,shortestPathToEndZone,setRoad,Maze}from"./engine/maze";
import {getMazePreset,mazePresets,MazePresetId}from"./engine/mazePresets";
import {buildDryTrace,createRobot,discoverAt,followStoredRoute,localSensorLabel,RobotState,shortestKnownRoute,DryRunResult,simplifyTurns}from"./engine/robot";
import {Cell,same}from"./types/maze";
import"./styles/app.css";

type Tool="draw"|"erase"|"start"|"end";type Phase="idle"|"dry"|"actual";
const DRY_CELL_SECONDS=.10,ACTUAL_CELL_SECONDS=.06;
export default function App(){
 const initial=sampleTwoPath();
 const[maze,setMaze]=useState<Maze>(()=>initial),[selectedMaze,setSelectedMaze]=useState<MazePresetId>("robo"),[robot,setRobot]=useState<RobotState>(()=>createRobot(initial.start)),[tool,setTool]=useState<Tool>("draw"),[dryResult,setDryResult]=useState<DryRunResult|null>(null),[dryIndex,setDryIndex]=useState(0),[actualIndex,setActualIndex]=useState(0),[phase,setPhase]=useState<Phase>("idle"),[speed,setSpeed]=useState(120),[message,setMessage]=useState("Ready. Robot memory is empty except for its starting position."),runId=useRef(0);
 const target=dryResult?.endCell??maze.end;
 const trueRoute=maze.referenceShortest,knownRoute=useMemo(()=>shortestKnownRoute(robot.known,maze.start,target),[robot.known,maze.start,target]),sensors=useMemo(()=>senseLocal(maze,robot.pos),[maze,robot.pos]),storedRoute=robot.route.length?robot.route:dryResult&&dryResult.endCell?shortestKnownRoute(dryResult.known,maze.start,dryResult.endCell):[];
 const benchmarkLen=trueRoute.length?trueRoute.length-1:null,robotLen=storedRoute.length?storedRoute.length-1:null,diff=benchmarkLen!==null&&robotLen!==null?robotLen-benchmarkLen:null,efficiency=benchmarkLen!==null&&robotLen?Math.round(benchmarkLen/robotLen*100):null;
 const dryTime=dryResult?Math.max(0,dryResult.trace.length-1)*DRY_CELL_SECONDS:0,actualTime=storedRoute.length?Math.max(0,storedRoute.length-1)*ACTUAL_CELL_SECONDS:0;
 const checkpoints=robot.discoveredCheckpoints.size;
 const score=useMemo(()=>{const A=25*checkpoints,B=robot.firstEndReached?30:0,C=dryResult?Math.max(0,180-dryTime):0,S=robotLen!==null&&benchmarkLen!==null&&robotLen===benchmarkLen?30:0,T=S?Math.max(0,150-actualTime):0,L=robot.led?5:0;return{A,B,C,S,T,L,total:A+B+C+S+T+L};},[checkpoints,robot.firstEndReached,dryResult,dryTime,robotLen,benchmarkLen,actualTime,robot.led]);
 function resetRobot(nextMaze=maze){runId.current+=1;setPhase("idle");setDryResult(null);setDryIndex(0);setActualIndex(0);setRobot(createRobot(nextMaze.start));setMessage("Robot reset. Hidden maze knowledge cleared.");}
 function loadMaze(id:MazePresetId){const copy=cloneMaze(getMazePreset(id));copy.referenceShortest=[];setSelectedMaze(id);setMaze(copy);resetRobot(copy);const preset=mazePresets.find(p=>p.id===id)!;setMessage(`${preset.name} loaded · ${preset.difficulty} test.`);}
 function edit(c:Cell){if(phase!=="idle")return;const next=cloneMaze(maze);if(tool==="draw")setRoad(next,c,true);if(tool==="erase"&&!same(c,next.start)&&!same(c,next.end))setRoad(next,c,false);if(tool==="start"){next.start={...c};setRoad(next,c,true)}if(tool==="end"){next.end={...c};setRoad(next,c,true)}next.referenceShortest=[];setMaze(next);resetRobot(next);setSelectedMaze("robo");}
 function startDryRun(){if(!has(maze,maze.start))return setMessage("START must be on the road.");if(!connected(maze))return setMessage("START → END box is not connected. Fix the maze first.");const benchmark=shortestPathToEndZone(maze,maze.start),snapshot=cloneMaze(maze);snapshot.referenceShortest=benchmark.map(c=>({...c}));runId.current+=1;setMaze(snapshot);const result=buildDryTrace(snapshot,snapshot.start);setDryResult(result);setDryIndex(0);setActualIndex(0);setRobot({...createRobot(snapshot.start),mode:"dry",status:"Exploring from local sensor data"});setPhase("dry");setMessage(`Dry Run started · observer benchmark: ${Math.max(0,benchmark.length-1)} moves.`);}
 function startActualRun(){if(!storedRoute.length)return setMessage("No stored route. Complete a Dry Run first.");runId.current+=1;setActualIndex(0);setRobot(followStoredRoute({...robot,route:storedRoute,led:false},storedRoute,0));setPhase("actual");setMessage("Actual Run: executing only the route learned during Dry Run.");}
 function pause(){runId.current+=1;setPhase("idle");setRobot(r=>({...r,mode:"done",status:"Paused"}));setMessage("Simulation paused.");}
 useEffect(()=>{if(phase!=="dry"||!dryResult)return;const token=runId.current,timer=window.setTimeout(()=>{if(token!==runId.current)return;const i=dryIndex+1;if(i>=dryResult.trace.length){const route=dryResult.endCell?shortestKnownRoute(dryResult.known,maze.start,dryResult.endCell):[],p=dryResult.trace[dryResult.trace.length-1];setRobot(r=>({...r,pos:{...p},trace:dryResult.trace,known:dryResult.known,backtracks:dryResult.backtracks,drySteps:dryResult.trace.length-1,route,mode:"done",status:dryResult.endReached?"END detected · route stored":"Dry Run stopped",firstEndReached:dryResult.endReached,led:dryResult.endReached,discoveredCheckpoints:new Set(dryResult.discoveredCheckpoints),junctions:dryResult.junctions,edgeTraversals:dryResult.edgeTraversals}));setDryIndex(dryResult.trace.length-1);setPhase("idle");setMessage(dryResult.endReached?`Dry Run complete · ${route.length?route.length-1:0} learned-route moves stored.`:"Dry Run ended without reaching END.");return;}const p=dryResult.trace[i];setDryIndex(i);setRobot(r=>{const n:RobotState={...r,pos:{...p},trace:[...r.trace,{...p}],known:{cells:new Set(r.known.cells),edges:new Set(r.known.edges)},drySteps:i,status:isEndCell(maze,p)?"END sensor active":"Exploring"};n.heading=direction(r.pos,p,r.heading);discoverAt(maze,n);if(dryResult.discoveredCheckpoints.has(`${p.x},${p.y}`))n.discoveredCheckpoints.add(`${p.x},${p.y}`);n.backtracks=countBacktracks(n.trace);if(dryResult.firstEndIndex===i)n.led=true;return n;});},speed);return()=>window.clearTimeout(timer)},[phase,dryResult,dryIndex,speed,maze]);
 useEffect(()=>{if(phase!=="actual"||!storedRoute.length)return;const token=runId.current,timer=window.setTimeout(()=>{if(token!==runId.current)return;const i=actualIndex+1;if(i>=storedRoute.length){const optimal=benchmarkLen!==null&&robotLen!==null&&robotLen===benchmarkLen;setRobot(r=>({...r,mode:"done",status:optimal?"Shortest Path complete":"Stored route complete",led:true,actualCursor:storedRoute.length-1,pos:{...storedRoute[storedRoute.length-1]}}));setActualIndex(storedRoute.length-1);setPhase("idle");setMessage(`Actual Run complete · ${robotLen??0} moves · ${optimal?"SHORTEST PATH":"stored route (not shortest)"}.`);return;}setActualIndex(i);setRobot(r=>followStoredRoute(r,storedRoute,i));},speed);return()=>window.clearTimeout(timer)},[phase,storedRoute,actualIndex,speed,benchmarkLen,robotLen]);
 return <main className="app"><header className="hero"><div><div className="eyebrow">TECHFEST IIT BOMBAY · MESHMErize 2026–27</div><h1>Autonomous Maze Robot Simulator</h1><p>Unknown-maze exploration, learned routing and real Meshmerize scoring.</p></div><div className="header-stats"><span>230 × 230 CM ARENA</span><span>30 MM LINE</span><span>400 MM END BOX</span></div></header>
 <section className="control-panel card"><div className="control-group"><span className="control-label">MAZE</span><select className="maze-select" value={selectedMaze} onChange={e=>loadMaze(e.target.value as MazePresetId)}>{mazePresets.map(p=><option key={p.id} value={p.id}>{p.name} · {p.difficulty}</option>)}</select><button onClick={()=>loadMaze("robo")}>Robo test</button><button onClick={()=>loadMaze("robo")}>Reset maze</button></div><div className="control-group"><span className="control-label">EDITOR</span>{(["draw","erase","start","end"]as Tool[]).map(t=><button key={t} className={tool===t?"active":""} onClick={()=>setTool(t)}>{t}</button>)}</div><div className="control-group run-controls"><span className="control-label">RUN</span><button className="primary" onClick={startDryRun} disabled={phase!=="idle"}>▶ Dry Run</button><button className="primary" onClick={startActualRun} disabled={phase!=="idle"||!storedRoute.length}>▶ Actual Run</button><button onClick={pause} disabled={phase==="idle"}>Pause</button><label className="speed">Animation <select value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[70,120,180,260].map(v=><option key={v} value={v}>{v} ms</option>)}</select></label></div></section>
 <div className="status-line"><span className={phase!=="idle"?"pulse":"dot"}/>{message}</div>
 <section className="workspace"><section className="card canvas-card"><div className="section-head arena-head"><div><h2>ARENA VIEW</h2><small>One view only · purple trace is what the robot has physically explored.</small></div><div className="led-indicator"><span className={`led-dot ${robot.led?"on":""}`}/><div><b>END LED</b><small>{robot.led?"ON":"OFF"}</small></div></div></div><div className="legend"><i className="legend-road"/> road <i className="legend-trace"/> explored <i className="legend-route"/> stored route <i className="legend-benchmark"/> observer benchmark</div><MazeCanvas maze={maze} robot={robot} tool={tool} onEdit={edit}/></section>
 <aside className="side-stack"><section className="card"><div className="section-head"><h2>Robot state</h2><span className={`mode ${robot.mode}`}>{robot.mode}</span></div><div className="stat-grid"><Stat label="Status" value={robot.status} wide/><Stat label="Position" value={`${robot.pos.x}, ${robot.pos.y}`}/><Stat label="Heading" value={robot.heading}/><Stat label="Known cells" value={robot.known.cells.size}/><Stat label="Known edges" value={robot.known.edges.size}/><Stat label="Junctions" value={robot.junctions.length}/><Stat label="Backtracks" value={robot.backtracks}/><Stat label="Checkpoints" value={`${checkpoints} / ${maze.checkpoints.size}`}/></div></section>
 <section className="card"><div className="section-head"><h2>Virtual sensors</h2><span>{sensors.length} local exits</span></div><div className="sensor-row">{(["N","E","S","W"]as const).map(d=>{const on=sensors.some(s=>s.dir===d);return <div key={d} className={`sensor ${on?"on":""}`}><b>{d}</b><span>{on?"ROAD":"WALL"}</span></div>})}</div><p className="sensor-readout">Local reading: <b>{localSensorLabel(maze,robot)}</b></p></section>
 <section className="card"><div className="section-head"><h2>Learned route</h2><span>{storedRoute.length?"stored":"none"}</span></div><div className="route-summary"><div><span>Benchmark</span><b>{benchmarkLen!==null?`${benchmarkLen} moves`:"—"}</b></div><div><span>Robot</span><b>{robotLen!==null?`${robotLen} moves`:"—"}</b></div><div><span>Difference</span><b>{diff===null?"—":diff===0?"Optimal":`+${diff}`}</b></div><div><span>Efficiency</span><b>{efficiency===null?"—":`${efficiency}%`}</b></div></div>{storedRoute.length>0&&<p className="route-turns">Turns: <b>{simplifyTurns(storedRoute).join(" ")||"START → END"}</b></p>}<p className="note">Actual Run uses the route learned during Dry Run.</p></section>
 <section className="card"><div className="section-head"><h2>Meshmerize score</h2><b className="total-score">{score.total}</b></div><div className="score-grid"><Stat label="A · Checkpoints" value={score.A}/><Stat label="B · Dry complete" value={score.B}/><Stat label="C · Dry time" value={score.C.toFixed(1)}/><Stat label="S · Shortest" value={score.S}/><Stat label="T · Actual time" value={score.T.toFixed(1)}/><Stat label="L · LED" value={score.L}/></div><div className="penalty">P · Penalties <b>0</b> <small>Simulator has no penalty events yet.</small></div></section>
 <section className="card rules-card"><h2>Robot rules</h2><ul><li>Starts with no maze, END or checkpoint map.</li><li>Only local sensor observations enter robot memory.</li><li>Trémaux-style edge memory: 0 → 1 → 2 traversals.</li><li>Checkpoints are detected when physically crossed; their coordinates are observer-only.</li><li>END is a sensor condition for the 400 × 400 mm white box.</li><li>Dry Run stops immediately at END; Actual Run replays the learned route.</li></ul><div className={`connectivity ${connected(maze)?"ok":"bad"}`}>{connected(maze)?"✓ START → END box connected":"! START → END box not connected"}</div></section></aside></section></main>;
}
function isEndCell(maze:Maze,c:Cell){return c.x>=maze.end.x-1&&c.x<=maze.end.x+2&&c.y>=maze.end.y-1&&c.y<=maze.end.y+2;}
function direction(a:Cell,b:Cell,fallback:RobotState["heading"]):RobotState["heading"]{if(b.x>a.x)return"E";if(b.x<a.x)return"W";if(b.y>a.y)return"S";if(b.y<a.y)return"N";return fallback;}
function countBacktracks(trace:Cell[]):number{let n=0;for(let i=2;i<trace.length;i++)if(same(trace[i],trace[i-2]))n++;return n;}
function Stat({label,value,wide,accent}:{label:string;value:React.ReactNode;wide?:boolean;accent?:boolean}){return <div className={`stat ${wide?"wide":""}`}><span>{label}</span><b className={accent?"accent-value":""}>{value}</b></div>}
