import React,{useEffect,useMemo,useRef,useState}from"react";
import MazeCanvas from"./components/MazeCanvas";
import {cloneMaze,connected,has,makeMaze,sampleTwoPath,senseLocal,shortestPath,setRoad,Maze}from"./engine/maze";
import {buildDryTrace,createRobot,discoverAt,followStoredRoute,localSensorLabel,RobotState,shortestKnownRoute,DryRunResult}from"./engine/robot";
import {Cell,same}from"./types/maze";
import"./styles/app.css";

type Tool="draw"|"erase"|"start"|"end";type Phase="idle"|"dry"|"actual";
export default function App(){
 const [maze,setMaze]=useState<Maze>(()=>sampleTwoPath()),[robot,setRobot]=useState<RobotState>(()=>createRobot(sampleTwoPath().start)),[tool,setTool]=useState<Tool>("draw"),[robotView,setRobotView]=useState(false),[dryResult,setDryResult]=useState<DryRunResult|null>(null),[dryIndex,setDryIndex]=useState(0),[actualIndex,setActualIndex]=useState(0),[phase,setPhase]=useState<Phase>("idle"),[speed,setSpeed]=useState(140),[message,setMessage]=useState("Ready. The robot starts with only its start cell."),runId=useRef(0);
 const trueRoute=useMemo(()=>shortestPath(maze,maze.start,maze.end),[maze]),knownRoute=useMemo(()=>shortestKnownRoute(robot.known,maze.start,maze.end),[robot.known,maze.start,maze.end]),sensors=useMemo(()=>senseLocal(maze,robot.pos),[maze,robot.pos]),actualRoute=dryResult?shortestKnownRoute(dryResult.known,maze.start,maze.end):[],routeGap=trueRoute.length&&knownRoute.length?knownRoute.length-trueRoute.length:null;
 function resetRobot(nextMaze=maze){runId.current+=1;setPhase("idle");setDryResult(null);setDryIndex(0);setActualIndex(0);setRobot(createRobot(nextMaze.start));setMessage("Robot reset. Hidden maze knowledge cleared.");}
 function loadMaze(next:Maze,text:string){const copy=cloneMaze(next);setMaze(copy);resetRobot(copy);setRobotView(false);setMessage(text);}
 function edit(c:Cell){if(phase!=="idle")return;const next=cloneMaze(maze);if(tool==="draw")setRoad(next,c,true);if(tool==="erase"&&!same(c,next.start)&&!same(c,next.end))setRoad(next,c,false);if(tool==="start"){next.start={...c};setRoad(next,c,true)}if(tool==="end"){next.end={...c};setRoad(next,c,true)}setMaze(next);resetRobot(next);}
 function startDryRun(){if(!has(maze,maze.start)||!has(maze,maze.end))return setMessage("Start and END must both be on the road.");if(!connected(maze))return setMessage("START → END is not connected. Fix the maze first.");runId.current+=1;const result=buildDryTrace(maze,maze.start);setDryResult(result);setDryIndex(0);setActualIndex(0);setRobot({...createRobot(maze.start),mode:"dry",status:"Exploring from local sensor data"});setPhase("dry");setRobotView(true);setMessage("Dry run: exploring from virtual sensor observations only.");}
 function startActualRun(){if(!actualRoute.length)return setMessage("No stored route. Complete a dry run first.");runId.current+=1;setActualIndex(0);setRobot(followStoredRoute({...robot,route:actualRoute},actualRoute,0));setPhase("actual");setRobotView(true);setMessage("Actual run: replaying the route stored during dry run.");}
 function pause(){runId.current+=1;setPhase("idle");setRobot(r=>({...r,mode:"done",status:"Paused"}));setMessage("Simulation paused.");}
 useEffect(()=>{if(phase!=="dry"||!dryResult)return;const token=runId.current,timer=window.setTimeout(()=>{if(token!==runId.current)return;const nextIndex=dryIndex+1;if(nextIndex>=dryResult.trace.length){const route=shortestKnownRoute(dryResult.known,maze.start,maze.end),finalPos=dryResult.trace[dryResult.trace.length-1];setRobot(r=>({...r,pos:{...finalPos},trace:dryResult.trace,known:dryResult.known,backtracks:dryResult.backtracks,drySteps:dryResult.trace.length-1,route,mode:"done",status:dryResult.endReached?"END reached — route stored":"Exploration stopped",firstEndReached:dryResult.endReached,led:dryResult.endReached}));setDryIndex(dryResult.trace.length-1);setPhase("idle");setMessage(route.length?`Dry run complete. Stored route: ${route.length} cells.`:"END reached, but no complete route is known.");return;}const pos=dryResult.trace[nextIndex];setDryIndex(nextIndex);setRobot(r=>{const next:RobotState={...r,pos:{...pos},trace:[...r.trace,{...pos}],known:{cells:new Set(r.known.cells),edges:new Set(r.known.edges)},drySteps:nextIndex,status:same(pos,maze.end)?"END reached":"Exploring"};next.heading=direction(r.pos,pos,r.heading);discoverAt(maze,next);next.backtracks=countBacktracks(next.trace);if(same(pos,maze.end))next.led=true;return next;});},speed);return()=>window.clearTimeout(timer)},[phase,dryResult,dryIndex,speed,maze]);
 useEffect(()=>{if(phase!=="actual"||!actualRoute.length)return;const token=runId.current,timer=window.setTimeout(()=>{if(token!==runId.current)return;const nextIndex=actualIndex+1;if(nextIndex>=actualRoute.length){setRobot(r=>({...r,mode:"done",status:"Actual run finished — END LED ON",led:true,actualCursor:actualRoute.length-1,pos:{...actualRoute[actualRoute.length-1]}}));setPhase("idle");setMessage("Actual run complete. No hidden-maze information was used.");return;}setActualIndex(nextIndex);setRobot(r=>followStoredRoute(r,actualRoute,nextIndex));},speed);return()=>window.clearTimeout(timer)},[phase,actualRoute,actualIndex,speed]);
 return <main className="app"><header className="hero"><div><div className="eyebrow">TECHFEST IIT BOMBAY · MESHMErize</div><h1>Autonomous Maze Robot Simulator</h1><p>Hidden organiser maze → local virtual sensors → robot memory → dry-run route → actual replay.</p></div><div className="header-stats"><span>23 × 23 GRID</span><span>AUTONOMOUS</span><span>NO MAP CHEAT</span></div></header>
 <section className="control-panel card"><div className="control-group"><span className="control-label">MAZE</span><button onClick={()=>loadMaze(sampleTwoPath(),"Loaded two-route test maze.")}>Two-route test</button><button onClick={()=>loadMaze(makeMaze(),"Blank maze loaded.")}>Blank</button><button onClick={()=>resetRobot()}>Reset robot</button></div><div className="control-group"><span className="control-label">EDITOR</span>{(["draw","erase","start","end"]as Tool[]).map(t=><button key={t} className={tool===t?"active":""} onClick={()=>setTool(t)}>{t}</button>)}</div><div className="control-group run-controls"><span className="control-label">RUN</span><button className="primary" onClick={startDryRun} disabled={phase!=="idle"}>▶ Dry Run</button><button className="primary" onClick={startActualRun} disabled={phase!=="idle"||!actualRoute.length}>▶ Actual Run</button><button onClick={pause} disabled={phase==="idle"}>Pause</button><label className="speed">Speed <select value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[80,140,220,320].map(v=><option key={v} value={v}>{v} ms</option>)}</select></label></div><button className="view-toggle" onClick={()=>setRobotView(v=>!v)}>{robotView?"Show main maze":"Show robot view"}</button></section>
 <div className="status-line"><span className={phase!=="idle"?"pulse":"dot"}/>{message}</div>
 <section className="workspace"><section className="card canvas-card"><div className="section-head"><div><h2>{robotView?"Robot View":"MAIN MAZE"}</h2><small>{robotView?"Only discovered cells and observed edges are rendered.":"Hidden environment. The robot cannot read this map."}</small></div><span className="legend"><i className="legend-road"/> road <i className="legend-route"/> stored route</span></div><MazeCanvas maze={maze} robot={robot} robotView={robotView} tool={tool} onEdit={edit}/></section>
 <aside className="side-stack"><section className="card"><div className="section-head"><h2>Robot state</h2><span className={`mode ${robot.mode}`}>{robot.mode}</span></div><div className="stat-grid"><Stat label="Status" value={robot.status} wide/><Stat label="Position" value={`${robot.pos.x}, ${robot.pos.y}`}/><Stat label="Heading" value={robot.heading}/><Stat label="Known cells" value={robot.known.cells.size}/><Stat label="Known edges" value={robot.known.edges.size}/><Stat label="Backtracks" value={robot.backtracks}/><Stat label="Dry steps" value={robot.drySteps}/><Stat label="Finish LED" value={robot.led?"ON":"OFF"} accent={robot.led}/></div></section>
 <section className="card"><div className="section-head"><h2>Virtual sensors</h2><span>{sensors.length} exits</span></div><div className="sensor-row">{(["N","E","S","W"]as const).map(d=>{const on=sensors.some(s=>s.dir===d);return <div key={d} className={`sensor ${on?"on":""}`}><b>{d}</b><span>{on?"ROAD":"WALL"}</span></div>})}</div><p className="sensor-readout">Reading: <b>{localSensorLabel(maze,robot)}</b></p></section>
 <section className="card"><div className="section-head"><h2>Route knowledge</h2><span>{actualRoute.length?"stored":"none"}</span></div><div className="route-summary"><div><span>Robot route</span><b>{knownRoute.length?`${knownRoute.length} cells`:"Not known"}</b></div><div><span>True shortest</span><b>{trueRoute.length?`${trueRoute.length} cells`:"No path"}</b></div>{routeGap!==null&&<div><span>Difference</span><b>{routeGap===0?"Optimal":`+${routeGap} cells`}</b></div>}</div><p className="note">True shortest is organiser/debug information only. The robot route is calculated from its discovered graph, never from the hidden maze.</p>{actualRoute.length>0&&<div className="route-code">{actualRoute.map((p,i)=><span key={`${p.x}-${p.y}-${i}`}>{i?" → ":""}{p.x},{p.y}</span>)}</div>}</section>
 <section className="card rules-card"><h2>Simulation rules</h2><ul><li>Robot starts with no maze map.</li><li>Only the current cell's N/E/S/W exits are sensed.</li><li>Observed edges are written into robot memory.</li><li>Dry run stops at the first END encounter.</li><li>Actual run replays the stored route only.</li></ul><div className={`connectivity ${connected(maze)?"ok":"bad"}`}>{connected(maze)?"✓ START → END connected":"! START → END not connected"}</div></section></aside></section></main>;
}
function direction(a:Cell,b:Cell,fallback:RobotState["heading"]):RobotState["heading"]{if(b.x>a.x)return"E";if(b.x<a.x)return"W";if(b.y>a.y)return"S";if(b.y<a.y)return"N";return fallback;}
function countBacktracks(trace:Cell[]):number{let count=0;for(let i=2;i<trace.length;i++)if(same(trace[i],trace[i-2]))count++;return count;}
function Stat({label,value,wide,accent}:{label:string;value:React.ReactNode;wide?:boolean;accent?:boolean}){return <div className={`stat ${wide?"wide":""}`}><span>{label}</span><b className={accent?"accent-value":""}>{value}</b></div>}
